@echo off
echo Setting up the ASF project...

echo Running check_imports.py to check if asf module can be imported...
python check_imports.py

echo Running install_asf.py to install asf module in development mode...
python install_asf.py

echo Running asf_path.py to add project root to Python path...
python asf_path.py

echo Running the backend server...
python run.py
